language: perl
---
language: perl

os:
  - linux
  # - osx

arch:
  - amd64
  - ppc64le
  - s390x
  # - arm64	# Gets 404 error

env:
  - AUTOMATED_TESTING=1
  - PERL_CPANM_OPT="--notest --force --skip-satisfied"

perl:
  - "5.30"
  # - "5.28" # Travis gets 404 errors trying to find some older perls
  - "5.26"
  - "5.24"
  # - "5.22"
  # - "5.20"
  # - "5.18"
  # - "5.16"
  # - "5.14"
  # - "5.12"
  # - "5.10"
  # - "5.8"
  # - "5.8.7"

matrix:
  allow_features:
    - perl: blead
  include:
    - perl: 5.30
      env: COVERAGE=1

sudo: false

before_script:
  - coverage-setup

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  # - sudo apt-get update -q
  - cpan-install --deps
  - cpan-install --coverage
  - cpanm -n Devel::Cover::Report::Coveralls Test::Script Test::Pod::Spelling::CommonMistakes Test::Portability::Files Test::Taint Test::Carp DBD::SQLite DBI CHI Test::Carp Test::Without::Module

script:
  # perl Makefile.PL && make && cover -test -report coveralls
  - prove -l -j$(test-jobs) $(test-files)

after_success:
  - coverage-report
