---
name: Test Code

# FIXME: IO::Compress::Brotli doesn't install on Windows

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-22.04
          - ubuntu-20.04
#         - windows-latest
        perl: ['5.36', '5.34', '5.32', '5.30', '5.28', '5.22']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn File::Spec ExtUtils::MakeMaker Test::Most
          cpanm -iqn --installdeps --notest .
      - name: Install Windows Dependencies
        if: matrix.os == 'windows-latest'
        run: cpanm -iqn Win32::Process IPC::System::Simple
      - name: Install non Windows Dependencies
        if: matrix.os != 'windows-latest'
        run: cpanm -iqn IO::Compress::Brotli
      - name: Run Tests
        run: prove -l -b t
        env:
          AUTHOR_TESTING: 1
