---
# See https://github.com/actions/virtual-environments

name: Test Code on Windows
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - windows-2019
        perl: ['5.38', '5.36', '5.34', '5.32', '5.30', '5.28']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: codecov/codecov-action@v5
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn --skip-satisfied File::Spec ExtUtils::MakeMaker Test::Harness
          cpanm -iqn --skip-satisfied Test::Carp Test::Compile
          cpanm -iqn --skip-satisfied --installdeps --notest .
          find . -name build.log | xargs cat
      - name: Run Tests
        run: prove -lv t
        env:
          AUTOMATED_TESTING: 1
